/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shoggoth_CONSTANTS_H
#define shoggoth_CONSTANTS_H

#include "shoggoth_types.h"



class shoggothConstants {
 public:
  shoggothConstants();

};

extern const shoggothConstants g_shoggoth_constants;



#endif
