/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "shoggoth_constants.h"



const shoggothConstants g_shoggoth_constants;

shoggothConstants::shoggothConstants() {
}



